export const japanCities = [
  "Sapporo",
  "Kushiro",
  "Sendai",
  "Niigata",
  "Tokyo",
  "Kanazawa",
  "Nagoya",
  "Osaka",
  "Hiroshima",
  "Kochi",
  "Fukuoka",
  "Kagoshima",
  "Naha",
];

export const japanCitiesInRegion = {
  Hokkaido: ["Sapporo", "Kushiro"],
  Tohoku: ["Sendai"],
  KantoKoshinetsu: ["Niigata", "Tokyo"],
  TokaiHokurikuKinki: ["Kanazawa", "Nagoya", "Osaka"],
  ChugokuShikoku: ["Hiroshima", "Kochi"],
  Kyushu: ["Fukuoka", "Kagoshima"],
  Okinawa: ["Naha"],
};

export const worldCities = [
  "New York",
  "Los Angeles",
  "Anchorage",
  "Honolulu",
  "Lima",
  "Sao Paulo",
  "Seoul",
  "Beijing",
  "Jakarta",
  "Moscow",
  "Sydney",
  "London",
  "Cairo",
  "Cape Town",
];

export const worldCitiesInRegion = {
  NorthAmerica: ["New York", "Los Angeles", "Anchorage", "Honolulu"],
  SouthAmerica: ["Lima", "Sao Paulo"],
  Asia: ["Seoul", "Beijing", "Jakarta", "Moscow"],
  Australia: ["Sydney"],
  Europe: ["London"],
  Africa: ["Cairo", "Cape Town"],
};

export const cities = [
  "Aarhus",
  "Aberdeen",
  "Abidjan",
  "Abu Dhabi",
  "Abuja",
  "Accra",
  "Adak",
  "Adamstown",
  "Adana",
  "Addis Ababa",
  "Adelaide",
  "Agartala",
  "Ahmedabad",
  "Albuquerque",
  "Alexandria",
  "Algiers",
  "Almaty",
  "Alofi",
  "Alor Star",
  "Ambon",
  "Amman",
  "Amritsar",
  "Amsterdam",
  "Anadyr (town)",
  "Anchorage",
  "Andorra la Vella",
  "Angra do Heroísmo",
  "Ankara",
  "Antananarivo",
  "Antofagasta",
  "Antwerp",
  "Apia",
  "Arbil",
  "Arequipa",
  "Ashgabat",
  "Asmara",
  "Assis",
  "Astana",
  "Asunción",
  "Athens",
  "Atlanta",
  "Auckland",
  "Austin",
  "Avarua",
  "Baghdad",
  "Bahía Blanca",
  "Baku",
  "Balikpapan",
  "Baltimore",
  "Bamako",
  "Banda Aceh",
  "Bandar Seri Begawan",
  "Bandung",
  "Bangalore",
  "Bangkok",
  "Bangui",
  "Banjul",
  "Barcelona",
  "Barranquilla",
  "Basra",
  "Basse-Terre",
  "Batticaloa",
  "Beijing",
  "Beirut",
  "Belfast",
  "Belgrade",
  "Belize City",
  "Belmopan",
  "Belém",
  "Bergen",
  "Berlin",
  "Bern",
  "Bilbao",
  "Birkirkara",
  "Birmingham",
  "Bishkek",
  "Bissau",
  "Blantyre",
  "Bloemfontein",
  "Boa Vista",
  "Bogor",
  "Bogotá",
  "Boston",
  "Brasília",
  "Bratislava",
  "Bratsk",
  "Brazzaville",
  "Bridgetown",
  "Brikama",
  "Brisbane",
  "Brussels",
  "Bucharest",
  "Budapest",
  "Buenos Aires",
  "Buffalo",
  "Bujumbura",
  "Bulawayo",
  "Bursa",
  "Busan",
  "Cairns",
  "Cairo",
  "Calama",
  "Calgary",
  "Cali",
  "Campinas",
  "Campo Grande",
  "Canberra",
  "Cannes",
  "Cape Town",
  "Caracas",
  "Cardiff",
  "Cartagena",
  "Casablanca",
  "Castries",
  "Cayenne",
  "Cebu City",
  "Chaguanas",
  "Changchun",
  "Charlotte",
  "Charlotte Amalie",
  "Charlottetown",
  "Chengdu",
  "Chennai",
  "Chiang Mai",
  "Chicago",
  "Chihuahua",
  "Chittagong",
  "Chişinău",
  "Chongjin",
  "Chongqing",
  "Christchurch",
  "Chuí",
  "Cincinnati",
  "City of Halifax",
  "City of San Marino",
  "Ciudad del Este",
  "Cleveland",
  "Cockburn Town",
  "Cologne",
  "Colombo",
  "Columbus",
  "Conakry",
  "Concepción",
  "Copenhagen",
  "Cork (city)",
  "Cotonou",
  "Cuiabá",
  "Curitiba",
  "Cusco",
  "Córdoba",
  "Da Nang",
  "Daegu",
  "Dakar",
  "Dalian",
  "Dallas",
  "Damascus",
  "Dammam",
  "Dar es Salaam",
  "Darwin",
  "Davao City",
  "Dededo",
  "Denpasar",
  "Denver",
  "Detroit",
  "Dhaka",
  "Dibrugarh",
  "Dili",
  "Djibouti (city)",
  "Dodoma",
  "Doha",
  "Dongguan",
  "Douala",
  "Douglas",
  "Dresden",
  "Dubai",
  "Dublin",
  "Dunedin",
  "Durango",
  "Durban",
  "Dushanbe",
  "Düsseldorf",
  "Edinburgh",
  "Edmonton",
  "El Aaiún",
  "El Paso",
  "Enugu",
  "Espoo",
  "Fairbanks",
  "Faisalabad",
  "Forked River",
  "Fort-de-France",
  "Fortaleza",
  "Francistown",
  "Frankfurt",
  "Fredericton",
  "Freetown",
  "Fukuoka",
  "Funafuti",
  "Gaborone",
  "Gangtok",
  "Gaza",
  "Gaziantep",
  "Gdańsk",
  "Geelong",
  "Geneva",
  "George Town",
  "Gibraltar",
  "Glasgow",
  "Gold Coast",
  "Gothenburg",
  "Graz",
  "Greenwich",
  "Guadalajara",
  "Guangzhou",
  "Guatemala City",
  "Guayaquil",
  "Guwahati",
  "Hagåtña",
  "Hai Phong",
  "Hamburg",
  "Hamilton",
  "Handan",
  "Hanga Roa",
  "Hangzhou",
  "Hanoi",
  "Hanover",
  "Harare",
  "Harbin",
  "Hargeisa",
  "Hat Yai",
  "Havana",
  "Helsinki",
  "Hilo",
  "Hiroshima",
  "Ho Chi Minh City",
  "Hobart",
  "Hong Kong",
  "Honiara",
  "Honolulu",
  "Horta (Azores)",
  "Houston",
  "Huế",
  "Hyderabad",
  "Ibadan",
  "Ibiza",
  "Ilhéus",
  "Iloilo City",
  "Incheon",
  "Indianapolis",
  "Innsbruck",
  "Invercargill",
  "Ipoh",
  "Iqaluit",
  "Iquique",
  "Iquitos",
  "Islamabad",
  "Istanbul",
  "Jacksonville",
  "Jaipur",
  "Jakarta",
  "Jamestown",
  "Jayapura",
  "Jeddah",
  "Jersey City",
  "Jerusalem",
  "Jinan",
  "Johannesburg",
  "Johor Bahru",
  "Juneau",
  "Kabul",
  "Kaesong",
  "Kaliningrad",
  "Kandahar",
  "Kandy",
  "Kano",
  "Kanpur",
  "Kansas City",
  "Kaohsiung",
  "Karachi",
  "Kathmandu",
  "Kawasaki",
  "Kharkiv",
  "Khartoum",
  "Kiev",
  "Kigali",
  "Kingston",
  "Kingstown",
  "Kinshasa",
  "Kobe",
  "Kolkata",
  "Konya",
  "Koror",
  "Kota Bharu",
  "Kota Kinabalu",
  "Koulikoro",
  "Kraków",
  "Kuala Lumpur",
  "Kuching",
  "Kunming",
  "Kuwait City",
  "Kyoto",
  "La Paz",
  "La Serena",
  "Labasa",
  "Lagos",
  "Lahore",
  "Lanzhou",
  "Las Palmas de Gran Canaria",
  "Las Vegas",
  "Leeds",
  "Leipzig",
  "Lhasa",
  "Libreville",
  "Lilongwe",
  "Lima",
  "Linz",
  "Lisbon",
  "Liverpool",
  "Livingstone",
  "Ljubljana",
  "Lobamba",
  "Lomé",
  "London",
  "Longyearbyen",
  "Los Angeles",
  "Louisville",
  "Luanda",
  "Lubumbashi",
  "Lucknow",
  "Ludhiana",
  "Lusaka",
  "Luxembourg (city)",
  "Luxor",
  "Lviv",
  "Lyon",
  "Macapá",
  "Macau",
  "Maceió",
  "Madrid",
  "Magadan",
  "Majuro",
  "Makassar",
  "Makati City",
  "Malabo",
  "Malacca Town",
  "Malang",
  "Malmö",
  "Malé",
  "Mamoudzou",
  "Managua",
  "Manama",
  "Manaus",
  "Manchester",
  "Mandurah",
  "Manila",
  "Manzini",
  "Maputo",
  "Maracaibo",
  "Marrakech",
  "Marseille",
  "Maseru",
  "Mashhad",
  "Mata-Utu",
  "Mbabane",
  "Mecca",
  "Medan",
  "Medellín",
  "Medina",
  "Melbourne",
  "Melekeok",
  "Memphis",
  "Mendoza",
  "Mersin",
  "Mexicali",
  "Mexico City",
  "Miami",
  "Milan",
  "Milwaukee",
  "Minneapolis",
  "Minsk",
  "Miri",
  "Mogadishu",
  "Monaco",
  "Monrovia",
  "Monterrey",
  "Montevideo",
  "Montreal",
  "Moroni",
  "Moscow",
  "Multan",
  "Mumbai",
  "Munich",
  "Murmansk",
  "Muscat",
  "Mwanza",
  "Málaga",
  "Mérida",
  "N'Djamena",
  "Nagoya",
  "Nagpur",
  "Nairobi",
  "Nakhon Ratchasima",
  "Namangan",
  "Nanjing",
  "Nanning",
  "Nantes",
  "Naples",
  "Nashville",
  "Nassau",
  "Naypyidaw",
  "Ndola",
  "New Delhi",
  "New Orleans",
  "New York City",
  "Newcastle",
  "Niamey",
  "Nice",
  "Nicosia",
  "Nizhny Novgorod",
  "Norilsk",
  "Nouakchott",
  "Nouméa",
  "Novosibirsk",
  "Nukulaelae",
  "Nukus",
  "Nukuʻalofa",
  "Nuuk",
  "Odessa",
  "Okinawa",
  "Oklahoma City",
  "Omdurman",
  "Omsk",
  "Oranjestad",
  "Osaka",
  "Oslo",
  "Ottawa",
  "Ouagadougou",
  "Padang",
  "Pago Pago",
  "Palembang",
  "Palikir",
  "Palma",
  "Panama City",
  "Papeete",
  "Paramaribo",
  "Paris",
  "Patna",
  "Pattaya",
  "Pekanbaru",
  "Pelotas",
  "Perm",
  "Perth",
  "Peshawar",
  "Petropavlovsk-Kamchatsky",
  "Philadelphia",
  "Phnom Penh",
  "Phoenix",
  "Phuket (city)",
  "Pittsburgh",
  "Podgorica",
  "Ponta Delgada",
  "Pontianak",
  "Port Blair",
  "Port Elizabeth",
  "Port Hedland",
  "Port Louis",
  "Port Moresby",
  "Port Said",
  "Port Vila",
  "Port of Spain",
  "Port-au-Prince",
  "Portland",
  "Porto",
  "Porto Alegre",
  "Porto Velho",
  "Porto-Novo",
  "Prague",
  "Praia",
  "Pretoria",
  "Pristina",
  "Providence",
  "Puebla",
  "Puerto Williams",
  "Pune",
  "Punta Arenas",
  "Pyongyang",
  "Qingdao",
  "Quebec City",
  "Quetzaltenango",
  "Quezon City",
  "Quito",
  "Rabat",
  "Rabi Island",
  "Raleigh",
  "Rawalpindi",
  "Recife",
  "Regina",
  "Reykjavík",
  "Riga",
  "Rio Branco",
  "Rio de Janeiro",
  "Riverside",
  "Riyadh",
  "Road Town",
  "Rochester",
  "Rockhampton",
  "Rome",
  "Rosario",
  "Roseau",
  "Rotterdam",
  "Sabha",
  "Sacramento",
  "Saint John",
  "Saint Petersburg",
  "Saint-Denis",
  "Saint-Pierre",
  "Saipan",
  "Salt Lake City",
  "Salzburg",
  "Samara",
  "San Antonio",
  "San Carlos de Bariloche",
  "San Diego",
  "San Fernando",
  "San Francisco",
  "San José",
  "San Juan",
  "San Salvador",
  "Sana'a",
  "Santa Cruz de Tenerife",
  "Santa Cruz de la Sierra",
  "Santiago",
  "Santiago de Cuba",
  "Santo Domingo",
  "Sapporo",
  "Sarajevo",
  "Saskatoon",
  "Seattle",
  "Semarang",
  "Seoul",
  "Serekunda",
  "Seville",
  "Shanghai",
  "Shenyang",
  "Shenzhen",
  "Shigatse",
  "Shijiazhuang",
  "Shillong",
  "Siem Reap",
  "Simferopol",
  "Singapore",
  "Sitka",
  "Skopje",
  "Sofia",
  "South Tarawa",
  "Split (city)",
  "Sri Jayawardenapura-Kotte",
  "Srinagar",
  "St. George's",
  "St. John's",
  "St. Louis",
  "Stanley",
  "Stepanakert",
  "Stockholm",
  "Strasbourg",
  "Stuttgart",
  "Sucre",
  "Suez",
  "Sukhumi",
  "Surabaya",
  "Surat",
  "Surat Thani",
  "Suva",
  "Sydney",
  "São José dos Campos",
  "São Paulo",
  "São Tomé",
  "Tabriz",
  "Tagbilaran",
  "Taichung",
  "Taipei",
  "Taiyuan",
  "Tallinn",
  "Tamale",
  "Tampa",
  "Tampere",
  "Tartu",
  "Tashkent",
  "Tbilisi",
  "Tegucigalpa",
  "Tehran",
  "Tel Aviv",
  "The Hague",
  "The Valley",
  "Thessaloniki",
  "Thimphu",
  "Thiès",
  "Tianjin",
  "Tijuana",
  "Timbuktu",
  "Tirana",
  "Tiraspol",
  "Tokyo",
  "Toronto",
  "Toulouse",
  "Townsville",
  "Tripoli",
  "Tskhinvali",
  "Tucson",
  "Tunis",
  "Turin",
  "Tórshavn",
  "Udon Thani",
  "Ulan Bator",
  "Ushuaia",
  "Vaduz",
  "Valdivia",
  "Valencia",
  "Valletta",
  "Valparaíso",
  "Vancouver",
  "Vatican City",
  "Veracruz",
  "Vienna",
  "Vientiane",
  "Vilnius",
  "Virginia Beach",
  "Vitória",
  "Vladivostok",
  "Warsaw",
  "Washington",
  "Wellington",
  "Weno",
  "Whitehorse",
  "Wichita",
  "Willemstad",
  "Winnipeg",
  "Wollongong",
  "Wonsan",
  "Wuhan",
  "Xi'an",
  "Xining",
  "Yakutsk",
  "Yamoussoukro",
  "Yangon",
  "Yaoundé",
  "Yaren District",
  "Yekaterinburg",
  "Yellowknife",
  "Yerevan",
  "Yogyakarta (city)",
  "Yokohama",
  "Zagreb",
  "Zamboanga City",
  "Zanzibar City",
  "Zapopan",
  "Zhengzhou",
  "Zürich",
  "Ürümqi",
  "İzmir",
];

export const citiesForSearch = [
  { title: "Aarhus" },
  { title: "Aberdeen" },
  { title: "Abidjan" },
  { title: "Abu Dhabi" },
  { title: "Abuja" },
  { title: "Accra" },
  { title: "Adak" },
  { title: "Adamstown" },
  { title: "Adana" },
  { title: "Addis Ababa" },
  { title: "Adelaide" },
  { title: "Agartala" },
  { title: "Ahmedabad" },
  { title: "Albuquerque" },
  { title: "Alexandria" },
  { title: "Algiers" },
  { title: "Almaty" },
  { title: "Alofi" },
  { title: "Alor Star" },
  { title: "Ambon" },
  { title: "Amman" },
  { title: "Amritsar" },
  { title: "Amsterdam" },
  { title: "Anadyr (town)" },
  { title: "Anchorage" },
  { title: "Andorra la Vella" },
  { title: "Angra do Heroísmo" },
  { title: "Ankara" },
  { title: "Antananarivo" },
  { title: "Antofagasta" },
  { title: "Antwerp" },
  { title: "Apia" },
  { title: "Arbil" },
  { title: "Arequipa" },
  { title: "Ashgabat" },
  { title: "Asmara" },
  { title: "Assis" },
  { title: "Astana" },
  { title: "Asunción" },
  { title: "Athens" },
  { title: "Atlanta" },
  { title: "Auckland" },
  { title: "Austin" },
  { title: "Avarua" },
  { title: "Baghdad" },
  { title: "Bahía Blanca" },
  { title: "Baku" },
  { title: "Balikpapan" },
  { title: "Baltimore" },
  { title: "Bamako" },
  { title: "Banda Aceh" },
  { title: "Bandar Seri Begawan" },
  { title: "Bandung" },
  { title: "Bangalore" },
  { title: "Bangkok" },
  { title: "Bangui" },
  { title: "Banjul" },
  { title: "Barcelona" },
  { title: "Barranquilla" },
  { title: "Basra" },
  { title: "Basse-Terre" },
  { title: "Batticaloa" },
  { title: "Beijing" },
  { title: "Beirut" },
  { title: "Belfast" },
  { title: "Belgrade" },
  { title: "Belize City" },
  { title: "Belmopan" },
  { title: "Belém" },
  { title: "Bergen" },
  { title: "Berlin" },
  { title: "Bern" },
  { title: "Bilbao" },
  { title: "Birkirkara" },
  { title: "Birmingham" },
  { title: "Bishkek" },
  { title: "Bissau" },
  { title: "Blantyre" },
  { title: "Bloemfontein" },
  { title: "Boa Vista" },
  { title: "Bogor" },
  { title: "Bogotá" },
  { title: "Boston" },
  { title: "Brasília" },
  { title: "Bratislava" },
  { title: "Bratsk" },
  { title: "Brazzaville" },
  { title: "Bridgetown" },
  { title: "Brikama" },
  { title: "Brisbane" },
  { title: "Brussels" },
  { title: "Bucharest" },
  { title: "Budapest" },
  { title: "Buenos Aires" },
  { title: "Buffalo" },
  { title: "Bujumbura" },
  { title: "Bulawayo" },
  { title: "Bursa" },
  { title: "Busan" },
  { title: "Cairns" },
  { title: "Cairo" },
  { title: "Calama" },
  { title: "Calgary" },
  { title: "Cali" },
  { title: "Campinas" },
  { title: "Campo Grande" },
  { title: "Canberra" },
  { title: "Cannes" },
  { title: "Cape Town" },
  { title: "Caracas" },
  { title: "Cardiff" },
  { title: "Cartagena" },
  { title: "Casablanca" },
  { title: "Castries" },
  { title: "Cayenne" },
  { title: "Cebu City" },
  { title: "Chaguanas" },
  { title: "Changchun" },
  { title: "Charlotte" },
  { title: "Charlotte Amalie" },
  { title: "Charlottetown" },
  { title: "Chengdu" },
  { title: "Chennai" },
  { title: "Chiang Mai" },
  { title: "Chicago" },
  { title: "Chihuahua" },
  { title: "Chittagong" },
  { title: "Chişinău" },
  { title: "Chongjin" },
  { title: "Chongqing" },
  { title: "Christchurch" },
  { title: "Chuí" },
  { title: "Cincinnati" },
  { title: "City of Halifax" },
  { title: "City of San Marino" },
  { title: "Ciudad del Este" },
  { title: "Cleveland" },
  { title: "Cockburn Town" },
  { title: "Cologne" },
  { title: "Colombo" },
  { title: "Columbus" },
  { title: "Conakry" },
  { title: "Concepción" },
  { title: "Copenhagen" },
  { title: "Cork (city)" },
  { title: "Cotonou" },
  { title: "Cuiabá" },
  { title: "Curitiba" },
  { title: "Cusco" },
  { title: "Córdoba" },
  { title: "Da Nang" },
  { title: "Daegu" },
  { title: "Dakar" },
  { title: "Dalian" },
  { title: "Dallas" },
  { title: "Damascus" },
  { title: "Dammam" },
  { title: "Dar es Salaam" },
  { title: "Darwin" },
  { title: "Davao City" },
  { title: "Dededo" },
  { title: "Denpasar" },
  { title: "Denver" },
  { title: "Detroit" },
  { title: "Dhaka" },
  { title: "Dibrugarh" },
  { title: "Dili" },
  { title: "Djibouti (city)" },
  { title: "Dodoma" },
  { title: "Doha" },
  { title: "Dongguan" },
  { title: "Douala" },
  { title: "Douglas" },
  { title: "Dresden" },
  { title: "Dubai" },
  { title: "Dublin" },
  { title: "Dunedin" },
  { title: "Durango" },
  { title: "Durban" },
  { title: "Dushanbe" },
  { title: "Düsseldorf" },
  { title: "Edinburgh" },
  { title: "Edmonton" },
  { title: "El Aaiún" },
  { title: "El Paso" },
  { title: "Enugu" },
  { title: "Espoo" },
  { title: "Fairbanks" },
  { title: "Faisalabad" },
  { title: "Forked River" },
  { title: "Fort-de-France" },
  { title: "Fortaleza" },
  { title: "Francistown" },
  { title: "Frankfurt" },
  { title: "Fredericton" },
  { title: "Freetown" },
  { title: "Fukuoka" },
  { title: "Funafuti" },
  { title: "Gaborone" },
  { title: "Gangtok" },
  { title: "Gaza" },
  { title: "Gaziantep" },
  { title: "Gdańsk" },
  { title: "Geelong" },
  { title: "Geneva" },
  { title: "George Town" },
  { title: "Gibraltar" },
  { title: "Glasgow" },
  { title: "Gold Coast" },
  { title: "Gothenburg" },
  { title: "Graz" },
  { title: "Greenwich" },
  { title: "Guadalajara" },
  { title: "Guangzhou" },
  { title: "Guatemala City" },
  { title: "Guayaquil" },
  { title: "Guwahati" },
  { title: "Hagåtña" },
  { title: "Hai Phong" },
  { title: "Hamburg" },
  { title: "Hamilton" },
  { title: "Handan" },
  { title: "Hanga Roa" },
  { title: "Hangzhou" },
  { title: "Hanoi" },
  { title: "Hanover" },
  { title: "Harare" },
  { title: "Harbin" },
  { title: "Hargeisa" },
  { title: "Hat Yai" },
  { title: "Havana" },
  { title: "Helsinki" },
  { title: "Hilo" },
  { title: "Hiroshima" },
  { title: "Ho Chi Minh City" },
  { title: "Hobart" },
  { title: "Hong Kong" },
  { title: "Honiara" },
  { title: "Honolulu" },
  { title: "Horta (Azores)" },
  { title: "Houston" },
  { title: "Huế" },
  { title: "Hyderabad" },
  { title: "Ibadan" },
  { title: "Ibiza" },
  { title: "Ilhéus" },
  { title: "Iloilo City" },
  { title: "Incheon" },
  { title: "Indianapolis" },
  { title: "Innsbruck" },
  { title: "Invercargill" },
  { title: "Ipoh" },
  { title: "Iqaluit" },
  { title: "Iquique" },
  { title: "Iquitos" },
  { title: "Islamabad" },
  { title: "Istanbul" },
  { title: "Jacksonville" },
  { title: "Jaipur" },
  { title: "Jakarta" },
  { title: "Jamestown" },
  { title: "Jayapura" },
  { title: "Jeddah" },
  { title: "Jersey City" },
  { title: "Jerusalem" },
  { title: "Jinan" },
  { title: "Johannesburg" },
  { title: "Johor Bahru" },
  { title: "Juneau" },
  { title: "Kabul" },
  { title: "Kaesong" },
  { title: "Kaliningrad" },
  { title: "Kandahar" },
  { title: "Kandy" },
  { title: "Kano" },
  { title: "Kanpur" },
  { title: "Kansas City" },
  { title: "Kaohsiung" },
  { title: "Karachi" },
  { title: "Kathmandu" },
  { title: "Kawasaki" },
  { title: "Kharkiv" },
  { title: "Khartoum" },
  { title: "Kiev" },
  { title: "Kigali" },
  { title: "Kingston" },
  { title: "Kingstown" },
  { title: "Kinshasa" },
  { title: "Kobe" },
  { title: "Kolkata" },
  { title: "Konya" },
  { title: "Koror" },
  { title: "Kota Bharu" },
  { title: "Kota Kinabalu" },
  { title: "Koulikoro" },
  { title: "Kraków" },
  { title: "Kuala Lumpur" },
  { title: "Kuching" },
  { title: "Kunming" },
  { title: "Kuwait City" },
  { title: "Kyoto" },
  { title: "La Paz" },
  { title: "La Serena" },
  { title: "Labasa" },
  { title: "Lagos" },
  { title: "Lahore" },
  { title: "Lanzhou" },
  { title: "Las Palmas de Gran Canaria" },
  { title: "Las Vegas" },
  { title: "Leeds" },
  { title: "Leipzig" },
  { title: "Lhasa" },
  { title: "Libreville" },
  { title: "Lilongwe" },
  { title: "Lima" },
  { title: "Linz" },
  { title: "Lisbon" },
  { title: "Liverpool" },
  { title: "Livingstone" },
  { title: "Ljubljana" },
  { title: "Lobamba" },
  { title: "Lomé" },
  { title: "London" },
  { title: "Longyearbyen" },
  { title: "Los Angeles" },
  { title: "Louisville" },
  { title: "Luanda" },
  { title: "Lubumbashi" },
  { title: "Lucknow" },
  { title: "Ludhiana" },
  { title: "Lusaka" },
  { title: "Luxembourg (city)" },
  { title: "Luxor" },
  { title: "Lviv" },
  { title: "Lyon" },
  { title: "Macapá" },
  { title: "Macau" },
  { title: "Maceió" },
  { title: "Madrid" },
  { title: "Magadan" },
  { title: "Majuro" },
  { title: "Makassar" },
  { title: "Makati City" },
  { title: "Malabo" },
  { title: "Malacca Town" },
  { title: "Malang" },
  { title: "Malmö" },
  { title: "Malé" },
  { title: "Mamoudzou" },
  { title: "Managua" },
  { title: "Manama" },
  { title: "Manaus" },
  { title: "Manchester" },
  { title: "Mandurah" },
  { title: "Manila" },
  { title: "Manzini" },
  { title: "Maputo" },
  { title: "Maracaibo" },
  { title: "Marrakech" },
  { title: "Marseille" },
  { title: "Maseru" },
  { title: "Mashhad" },
  { title: "Mata-Utu" },
  { title: "Mbabane" },
  { title: "Mecca" },
  { title: "Medan" },
  { title: "Medellín" },
  { title: "Medina" },
  { title: "Melbourne" },
  { title: "Melekeok" },
  { title: "Memphis" },
  { title: "Mendoza" },
  { title: "Mersin" },
  { title: "Mexicali" },
  { title: "Mexico City" },
  { title: "Miami" },
  { title: "Milan" },
  { title: "Milwaukee" },
  { title: "Minneapolis" },
  { title: "Minsk" },
  { title: "Miri" },
  { title: "Mogadishu" },
  { title: "Monaco" },
  { title: "Monrovia" },
  { title: "Monterrey" },
  { title: "Montevideo" },
  { title: "Montreal" },
  { title: "Moroni" },
  { title: "Moscow" },
  { title: "Multan" },
  { title: "Mumbai" },
  { title: "Munich" },
  { title: "Murmansk" },
  { title: "Muscat" },
  { title: "Mwanza" },
  { title: "Málaga" },
  { title: "Mérida" },
  { title: "N'Djamena" },
  { title: "Nagoya" },
  { title: "Nagpur" },
  { title: "Nairobi" },
  { title: "Nakhon Ratchasima" },
  { title: "Namangan" },
  { title: "Nanjing" },
  { title: "Nanning" },
  { title: "Nantes" },
  { title: "Naples" },
  { title: "Nashville" },
  { title: "Nassau" },
  { title: "Naypyidaw" },
  { title: "Ndola" },
  { title: "New Delhi" },
  { title: "New Orleans" },
  { title: "New York City" },
  { title: "Newcastle" },
  { title: "Niamey" },
  { title: "Nice" },
  { title: "Nicosia" },
  { title: "Nizhny Novgorod" },
  { title: "Norilsk" },
  { title: "Nouakchott" },
  { title: "Nouméa" },
  { title: "Novosibirsk" },
  { title: "Nukulaelae" },
  { title: "Nukus" },
  { title: "Nukuʻalofa" },
  { title: "Nuuk" },
  { title: "Odessa" },
  { title: "Okinawa" },
  { title: "Oklahoma City" },
  { title: "Omdurman" },
  { title: "Omsk" },
  { title: "Oranjestad" },
  { title: "Osaka" },
  { title: "Oslo" },
  { title: "Ottawa" },
  { title: "Ouagadougou" },
  { title: "Padang" },
  { title: "Pago Pago" },
  { title: "Palembang" },
  { title: "Palikir" },
  { title: "Palma" },
  { title: "Panama City" },
  { title: "Papeete" },
  { title: "Paramaribo" },
  { title: "Paris" },
  { title: "Patna" },
  { title: "Pattaya" },
  { title: "Pekanbaru" },
  { title: "Pelotas" },
  { title: "Perm" },
  { title: "Perth" },
  { title: "Peshawar" },
  { title: "Petropavlovsk-Kamchatsky" },
  { title: "Philadelphia" },
  { title: "Phnom Penh" },
  { title: "Phoenix" },
  { title: "Phuket (city)" },
  { title: "Pittsburgh" },
  { title: "Podgorica" },
  { title: "Ponta Delgada" },
  { title: "Pontianak" },
  { title: "Port Blair" },
  { title: "Port Elizabeth" },
  { title: "Port Hedland" },
  { title: "Port Louis" },
  { title: "Port Moresby" },
  { title: "Port Said" },
  { title: "Port Vila" },
  { title: "Port of Spain" },
  { title: "Port-au-Prince" },
  { title: "Portland" },
  { title: "Porto" },
  { title: "Porto Alegre" },
  { title: "Porto Velho" },
  { title: "Porto-Novo" },
  { title: "Prague" },
  { title: "Praia" },
  { title: "Pretoria" },
  { title: "Pristina" },
  { title: "Providence" },
  { title: "Puebla" },
  { title: "Puerto Williams" },
  { title: "Pune" },
  { title: "Punta Arenas" },
  { title: "Pyongyang" },
  { title: "Qingdao" },
  { title: "Quebec City" },
  { title: "Quetzaltenango" },
  { title: "Quezon City" },
  { title: "Quito" },
  { title: "Rabat" },
  { title: "Rabi Island" },
  { title: "Raleigh" },
  { title: "Rawalpindi" },
  { title: "Recife" },
  { title: "Regina" },
  { title: "Reykjavík" },
  { title: "Riga" },
  { title: "Rio Branco" },
  { title: "Rio de Janeiro" },
  { title: "Riverside" },
  { title: "Riyadh" },
  { title: "Road Town" },
  { title: "Rochester" },
  { title: "Rockhampton" },
  { title: "Rome" },
  { title: "Rosario" },
  { title: "Roseau" },
  { title: "Rotterdam" },
  { title: "Sabha" },
  { title: "Sacramento" },
  { title: "Saint John" },
  { title: "Saint Petersburg" },
  { title: "Saint-Denis" },
  { title: "Saint-Pierre" },
  { title: "Saipan" },
  { title: "Salt Lake City" },
  { title: "Salzburg" },
  { title: "Samara" },
  { title: "San Antonio" },
  { title: "San Carlos de Bariloche" },
  { title: "San Diego" },
  { title: "San Fernando" },
  { title: "San Francisco" },
  { title: "San José" },
  { title: "San Juan" },
  { title: "San Salvador" },
  { title: "Sana'a" },
  { title: "Santa Cruz de Tenerife" },
  { title: "Santa Cruz de la Sierra" },
  { title: "Santiago" },
  { title: "Santiago de Cuba" },
  { title: "Santo Domingo" },
  { title: "Sapporo" },
  { title: "Sarajevo" },
  { title: "Saskatoon" },
  { title: "Seattle" },
  { title: "Semarang" },
  { title: "Seoul" },
  { title: "Serekunda" },
  { title: "Seville" },
  { title: "Shanghai" },
  { title: "Shenyang" },
  { title: "Shenzhen" },
  { title: "Shigatse" },
  { title: "Shijiazhuang" },
  { title: "Shillong" },
  { title: "Siem Reap" },
  { title: "Simferopol" },
  { title: "Singapore" },
  { title: "Sitka" },
  { title: "Skopje" },
  { title: "Sofia" },
  { title: "South Tarawa" },
  { title: "Split (city)" },
  { title: "Sri Jayawardenapura-Kotte" },
  { title: "Srinagar" },
  { title: "St. George's" },
  { title: "St. John's" },
  { title: "St. Louis" },
  { title: "Stanley" },
  { title: "Stepanakert" },
  { title: "Stockholm" },
  { title: "Strasbourg" },
  { title: "Stuttgart" },
  { title: "Sucre" },
  { title: "Suez" },
  { title: "Sukhumi" },
  { title: "Surabaya" },
  { title: "Surat" },
  { title: "Surat Thani" },
  { title: "Suva" },
  { title: "Sydney" },
  { title: "São José dos Campos" },
  { title: "São Paulo" },
  { title: "São Tomé" },
  { title: "Tabriz" },
  { title: "Tagbilaran" },
  { title: "Taichung" },
  { title: "Taipei" },
  { title: "Taiyuan" },
  { title: "Tallinn" },
  { title: "Tamale" },
  { title: "Tampa" },
  { title: "Tampere" },
  { title: "Tartu" },
  { title: "Tashkent" },
  { title: "Tbilisi" },
  { title: "Tegucigalpa" },
  { title: "Tehran" },
  { title: "Tel Aviv" },
  { title: "The Hague" },
  { title: "The Valley" },
  { title: "Thessaloniki" },
  { title: "Thimphu" },
  { title: "Thiès" },
  { title: "Tianjin" },
  { title: "Tijuana" },
  { title: "Timbuktu" },
  { title: "Tirana" },
  { title: "Tiraspol" },
  { title: "Tokyo" },
  { title: "Toronto" },
  { title: "Toulouse" },
  { title: "Townsville" },
  { title: "Tripoli" },
  { title: "Tskhinvali" },
  { title: "Tucson" },
  { title: "Tunis" },
  { title: "Turin" },
  { title: "Tórshavn" },
  { title: "Udon Thani" },
  { title: "Ulan Bator" },
  { title: "Ushuaia" },
  { title: "Vaduz" },
  { title: "Valdivia" },
  { title: "Valencia" },
  { title: "Valletta" },
  { title: "Valparaíso" },
  { title: "Vancouver" },
  { title: "Vatican City" },
  { title: "Veracruz" },
  { title: "Vienna" },
  { title: "Vientiane" },
  { title: "Vilnius" },
  { title: "Virginia Beach" },
  { title: "Vitória" },
  { title: "Vladivostok" },
  { title: "Warsaw" },
  { title: "Washington" },
  { title: "Wellington" },
  { title: "Weno" },
  { title: "Whitehorse" },
  { title: "Wichita" },
  { title: "Willemstad" },
  { title: "Winnipeg" },
  { title: "Wollongong" },
  { title: "Wonsan" },
  { title: "Wuhan" },
  { title: "Xi'an" },
  { title: "Xining" },
  { title: "Yakutsk" },
  { title: "Yamoussoukro" },
  { title: "Yangon" },
  { title: "Yaoundé" },
  { title: "Yaren District" },
  { title: "Yekaterinburg" },
  { title: "Yellowknife" },
  { title: "Yerevan" },
  { title: "Yogyakarta (city)" },
  { title: "Yokohama" },
  { title: "Zagreb" },
  { title: "Zamboanga City" },
  { title: "Zanzibar City" },
  { title: "Zapopan" },
  { title: "Zhengzhou" },
  { title: "Zürich" },
  { title: "Ürümqi" },
  { title: "İzmir" },
];
